# Generated by Django 5.1.7 on 2025-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience_full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
