# Generated by Django 5.1.7 on 2025-03-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
