# Generated by Django 5.1.7 on 2025-03-11 15:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_experience_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
