# Generated by Django 5.1.7 on 2025-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_experience_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='image',
            new_name='experience_image',
        ),
    ]
