# Generated by Django 5.1.7 on 2025-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_guest_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
