# Generated by Django 4.2.18 on 2025-03-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.IntegerField(verbose_name="Number of guests, don't forget yourself!"),
        ),
    ]
